export const BEGIN_LOGIN = "BEGIN_LOGIN";
export const LOGIN = "LOGIN";
export const UPDATE_DATA_LOGIN = "UPDATE_DATA_LOGIN";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GOT_DATA_LOGIN = "GOT_DATA_LOGIN";
export const LOGOUT = "LOGOUT";
export const BEGIN_REGISTER = "BEGIN_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const SKIP_LOGIN = "SKIP_LOGIN";
export const GET_DATA = "GET_DATA";

export const BEGIN_GET_LIST_TREND = "BEGIN_GET_LIST_TREND";
export const GET_LIST_TREND_SUCCESS = "GET_LIST_TREND_SUCCESS";
export const BEGIN_GET_MORE_LIST_TREND = "BEGIN_GET_MORE_LIST_TREND";
export const GET_MORE_LIST_TREND_SUCCESS = "GET_MORE_LIST_TREND_SUCCESS";
export const BEGIN_REFRESH_LIST_TREND = "BEGIN_REFRESH_LIST_TREND";
export const REFRESH_LIST_TREND_SUCCESS = "REFRESH_LIST_TREND_SUCCESS";
export const REFRESH_LIST_TREND_ERROR = "REFRESH_LIST_TREND_ERROR";

export const BEGIN_GET_DETAIL_TREND = "BEGIN_GET_DETAIL_TREND";
export const GET_DETAIL_TREND_SUCCESS = "GET_DETAIL_TREND_SUCCESS";
